server:
  port: 8080 # Puerto interno del contenedor del Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Productos
        - id: productos-service
          uri: lb://PRODUCTOS-SERVICE # Usar el nombre de Eureka en mayúsculas
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=1 # Elimina '/api'

        # Categorias (Parte de Productos, rutea al mismo servicio)
        - id: categorias-service
          uri: lb://PRODUCTOS-SERVICE # Usar el nombre de Eureka en mayúsculas
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=1 # Elimina '/api'

        # Identity - Corregido para Postman
        - id: identity-service
          uri: lb://IDENTITY-SERVICE # Usar el nombre de Eureka en mayúsculas
          predicates:
            - Path=/identity/auth/** # Coincide con /identity/auth/login
          filters:
            - StripPrefix=1 # Elimina '/identity' antes de enviar a IDENTITY-SERVICE

        # Usuarios
        - id: usuario-service
          uri: lb://USUARIO-SERVICE # Usar el nombre de Eureka en mayúsculas
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=1

        - id: ventas-service
          uri: lb://VENTAS-SERVICE
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      # Esta configuración debería ser sobreescrita por la variable de entorno en docker-compose.yml
      # Pero si no, asegúrate de que esté configurada para el entorno Docker
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true