server:
  port: 8080 # Puerto interno del Gateway dentro del contenedor

spring:
  application:
    name: api-gateway # Nombre del servicio para Eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Productos
        - id: productos-service
          uri: lb://PRODUCTOS-SERVICE # Usar el nombre de servicio en MAYÚSCULAS para Eureka
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=2

        # Categorias (Asumiendo que están en el mismo servicio de productos)
        - id: categorias-service
          uri: lb://PRODUCTOS-SERVICE
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=2 # Elimina /api/categorias del path

        # Identity - Autenticación manual (registro, login)
        - id: identity-service-auth
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 # Elimina /auth del path

        # Rutas OAuth2 (importante que se enruten correctamente al Identity Service)
        - id: oauth2-authorization-google # Ruta para iniciar el flujo de Google OAuth2
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/oauth2/authorization/google
          filters:
            - StripPrefix=0 # Pasa la ruta tal cual al Identity Service

        - id: oauth2-callback-google # Ruta para el callback de Google OAuth2
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/login/oauth2/code/google
          filters:
            - StripPrefix=0 # Pasa la ruta tal cual al Identity Service

        # Perfiles de Usuario
        - id: perfiles-usuario-service
          uri: lb://USUARIO-SERVICE # Usar el nombre de servicio en MAYÚSCULAS para Eureka
          predicates:
            - Path=/api/perfiles-usuario/**
          filters:
            - StripPrefix=2 # Elimina /api/perfiles-usuario del path

        # Ventas Service
        - id: ventas-service
          uri: lb://VENTAS-SERVICE # Usar el nombre de servicio en MAYÚSCULAS para Eureka
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=2 # Elimina /api/ventas del path

jwt: # JWT_SECRET se inyecta como variable de entorno en docker-compose.yml
  secret: "${JWT_SECRET}"
  # Aquí puedes añadir expiration si no lo haces en identity-service o si necesitas una diferente para el gateway
  # expiration: 3600 # Ejemplo: 1 hora
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true