# api-gateway.yml (EN TU REPOSITORIO GIT DEL CONFIG SERVER)
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # ... (tus rutas existentes) ...
        - id: productos-service
          uri: lb://PRODUCTOS-SERVICE
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=1
        - id: categorias-service
          uri: lb://PRODUCTOS-SERVICE
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=1
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/auth/**
          filters:
            - StripPrefix=1
        - id: google-oauth2-init
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/oauth2/authorization/google
        - id: google-oauth2-callback
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/login/oauth2/code/google
        - id: perfiles-usuario-service
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/api/perfiles-usuario/**
          filters:
            - StripPrefix=1
        - id: ventas-service
          uri: lb://VENTAS-SERVICE
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=1
#jwt: # <--- COMENTA O ELIMINA ESTO SI EL JWT_SECRET LO OBTIENE DEL .env VIA DOCKER COMPOSE
#  secret: "${JWT_SECRET}"
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true