# Nombre: api-gateway-docker.yml
# El Config Server lo encontrará por "api-gateway" + profile "docker"
server:
  port: 8080 # Puerto interno del Gateway dentro del contenedor

spring:
  application:
    name: api-gateway # Nombre del servicio para Eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Productos
        - id: productos-service
          uri: lb://PRODUCTOS-SERVICE
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=2

        # Categorias
        - id: categorias-service
          uri: lb://PRODUCTOS-SERVICE
          predicates:
            - Path=/api/categorias/**
          filters:
            - StripPrefix=2

        # Identity - Autenticación
        - id: identity-service-auth
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Rutas OAuth2
        - id: oauth2-authorization-google
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/oauth2/authorization/google
          filters:
            - StripPrefix=0

        - id: oauth2-callback-google
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/login/oauth2/code/google
          filters:
            - StripPrefix=0

        # Perfiles de Usuario
        - id: perfiles-usuario-service
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/api/perfiles-usuario/**
          filters:
            - StripPrefix=2

        # Ventas Service
        - id: ventas-service
          uri: lb://VENTAS-SERVICE
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
