server:
  port: 9000

spring:
  datasource:
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;database=BD_Usuarios;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: netcompany
    # ¡LA CONTRASEÑA, CLIENT_ID, CLIENT_SECRET YA NO ESTÁN AQUÍ!
    # Se inyectan como variables de entorno en docker-compose.yml
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

  security:
    oauth2:
      client:
        registration:
          google:
            # client-id y client-secret se obtienen de las variables de entorno
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: email

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  # jwt.secret se obtiene de la variable de entorno
  expiration: 86400000

frontend:
# frontend.redirect-url se obtiene de la variable de entorno