server:
  port: 9000 # Puerto estándar para un servicio de identidad

spring:
  datasource:
    # Usamos las mismas credenciales que ya tienes
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;database=DB_Identity;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: netcompany
    password: "@Isac922024126"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

# Configuración para registrarse en Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# --- SECCIÓN CLAVE PARA JWT ---
# Aquí definimos las propiedades para generar los tokens.
jwt:
  # ¡¡IMPORTANTE!! Esta debe ser EXACTAMENTE la misma clave secreta que tienes en tu API Gateway.
  secret: "claveSuperSecretaParaGenerarTokensSegurosDeNetShop123456"
  # Tiempo de expiración del token en milisegundos (ej. 24 horas)
  expiration: 86400000
