server:
  port: 9000 # Puerto interno del servicio

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;database=BD_NetUsuarios;encrypt=true;trustServerCertificate=true
    username: netcompany
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${EXPIRATION}

  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: email
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true