server:
  port: 8110

spring:
  application:
    name: usuario-service  # 🔹 Asegura que el nombre sea igual en Eureka y en el Config Server

  datasource:
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;database=DB_Usuarios;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: netcompany
    password: "@Isac922024126"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    connection-timeout: 30000
    pool-name: HikariPool-NetShop

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  # 🔹 Opcional pero útil: información del servicio para el panel de Eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
