server:
  port: 8200

spring:
  application:
    name: ventas-service # Asegúrate de que este nombre esté presente para Eureka/Feign
  datasource:
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;database=DB_Ventas;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: netcompany
    password: "@Isac922024126"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  hikari:
    pool-name: HikariPool-Ventas
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configuración para registrarse en Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/