server:
  port: 8200

spring:
  application:
    name: ventas-service
  datasource:
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;database=DB_Ventas;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: netcompany
    password: "@Isac922024126"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update # Cambia a 'validate' o 'none' en producción
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  hikari:
    pool-name: HikariPool-Ventas
  rabbitmq:
    host: rabbitmq # Usa el nombre del servicio de Docker Compose aquí
    port: 5672
    username: guest
    password: guest

# Configuración para registrarse en Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
